const ORDER_LINKS = {
  wolt: 'https://wolt.com/bg/bgr/plovdiv/restaurant/28-grill',
  takeaway: 'https://www.takeaway.com/bg/menu/28-grill28-gril',
  bolt: 'https://food.bolt.eu/bg-bg/2128-plovdiv/p/191640-28-grill/',
};

const I = {
  brioche: { bg: 'Бриош', en: 'Brioche', fr: 'Brioche', it: 'Brioche', es: 'Brioche', el: 'Brioche' },
  redOnion: { bg: 'Червен лук', en: 'Red onion', fr: 'Oignon rouge', it: 'Cipolla rossa', es: 'Cebolla roja', el: 'Κόκκινο κρεμμύδι' },
  sauce28: { bg: 'Сос 28', en: 'Sauce 28', fr: 'Sauce 28', it: 'Salsa 28', es: 'Salsa 28', el: 'Sauce 28' },
  cheddar: { bg: 'Чедър', en: 'Cheddar', fr: 'Cheddar', it: 'Cheddar', es: 'Cheddar', el: 'Cheddar' },
  cheddarSlice: { bg: 'Чедър резен', en: 'Cheddar slice', fr: 'Tranche cheddar', it: 'Cheddar a fette', es: 'Loncha cheddar', el: 'Φέτα cheddar' },
  cheddarSauce: { bg: 'Чедър сос', en: 'Cheddar sauce', fr: 'Sauce cheddar', it: 'Salsa cheddar', es: 'Salsa cheddar', el: 'Σάλτσα cheddar' },
  bacon: { bg: 'Бекон', en: 'Bacon', fr: 'Bacon', it: 'Bacon', es: 'Bacon', el: 'Μπέικον' },
  pickles: { bg: 'Кисели краставички', en: 'Pickles', fr: 'Cornichons', it: 'Cetriolini', es: 'Pepinillos', el: 'Πίκλες' },
  ketchup: { bg: 'Кетчуп Heinz', en: 'Heinz ketchup', fr: 'Ketchup Heinz', it: 'Ketchup Heinz', es: 'Ketchup Heinz', el: 'Ketchup Heinz' },
  hotSauce: { bg: 'Лют сос', en: 'Hot sauce', fr: 'Sauce piquante', it: 'Salsa piccante', es: 'Salsa picante', el: 'Καυτερή σάλτσα' },
  gouda: { bg: 'Gouda', en: 'Gouda', fr: 'Gouda', it: 'Gouda', es: 'Gouda', el: 'Gouda' },
  jalapeno: { bg: 'Jalapeño', en: 'Jalapeño', fr: 'Jalapeño', it: 'Jalapeño', es: 'Jalapeño', el: 'Jalapeño' },
  lettuce: { bg: 'Салата', en: 'Lettuce', fr: 'Salade', it: 'Insalata', es: 'Lechuga', el: 'Μαρούλι' },
  tomato: { bg: 'Домати', en: 'Tomato', fr: 'Tomate', it: 'Pomodoro', es: 'Tomate', el: 'Ντομάτα' },
  friedOnion: { bg: 'Пържен лук', en: 'Fried onion', fr: 'Oignon frit', it: 'Cipolla fritta', es: 'Cebolla frita', el: 'Τηγανητό κρεμμύδι' },
  greenLettuce: { bg: 'Зелена салата', en: 'Green lettuce', fr: 'Laitue verte', it: 'Lattuga verde', es: 'Lechuga verde', el: 'Πράσινο μαρούλι' },
  bbq: { bg: 'Барбекю', en: 'BBQ', fr: 'BBQ', it: 'BBQ', es: 'BBQ', el: 'BBQ' },
  roastedOnion: { bg: 'Печен лук', en: 'Roasted onion', fr: 'Oignon rôti', it: 'Cipolla arrostita', es: 'Cebolla asada', el: 'Ψητό κρεμμύδι' },
  specialSauce: { bg: 'Специален сос', en: 'Special sauce', fr: 'Sauce spéciale', it: 'Salsa speciale', es: 'Salsa especial', el: 'Ειδική σάλτσα' },
  egg: { bg: 'Яйце', en: 'Egg', fr: 'Œuf', it: 'Uovo', es: 'Huevo', el: 'Αυγό' },
  ranch: { bg: 'Ранч', en: 'Ranch', fr: 'Ranch', it: 'Ranch', es: 'Ranch', el: 'Ranch' },
  peanutSauce: { bg: 'Убийствен сос с фъстъчено масло', en: 'Killer peanut butter sauce', fr: 'Sauce killer au beurre de cacahuète', it: 'Salsa killer al burro di arachidi', es: 'Salsa killer de mantequilla de cacahuete', el: 'Killer σάλτσα με φυστικοβούτυρο' },
  stewedFriedOnion: { bg: 'Задушен и пържен лук', en: 'Stewed and fried onion', fr: 'Oignon confit et frit', it: 'Cipolla stufata e fritta', es: 'Cebolla guisada y frita', el: 'Μαγειρεμένο και τηγανητό κρεμμύδι' },
  mayoBacon: { bg: 'Бекон майонеза', en: 'Bacon mayo', fr: 'Mayo bacon', it: 'Mayo bacon', es: 'Mayo bacon', el: 'Μαγιονέζα μπέικον' },
  onion: { bg: 'Лук', en: 'Onion', fr: 'Oignon', it: 'Cipolla', es: 'Cebolla', el: 'Κρεμμύδι' },
  chicken: { bg: '2 пилешки филенца', en: '2 chicken fillets', fr: '2 filets de poulet', it: '2 filetti di pollo', es: '2 filetes de pollo', el: '2 φιλέτα κοτόπουλο' },
  liquidCheddar: { bg: 'Течен чедър', en: 'Liquid cheddar', fr: 'Cheddar fondu', it: 'Cheddar fuso', es: 'Cheddar líquido', el: 'Υγρό cheddar' },
  coleslaw: { bg: 'Coleslaw', en: 'Coleslaw', fr: 'Coleslaw', it: 'Coleslaw', es: 'Coleslaw', el: 'Coleslaw' },
  soyBurger: { bg: 'Соев бургер', en: 'Soy burger', fr: 'Burger soja', it: 'Burger di soia', es: 'Burger de soja', el: 'Burger σόγιας' },
  mayo: { bg: 'Майонеза', en: 'Mayo', fr: 'Mayo', it: 'Mayo', es: 'Mayo', el: 'Μαγιονέζα' },
  guacamole: { bg: 'Гуакамоле', en: 'Guacamole', fr: 'Guacamole', it: 'Guacamole', es: 'Guacamole', el: 'Guacamole' },
};

function text(bg, en, fr = en, it = en, es = en, el = en) {
  return { bg, en, fr, it, es, el };
}

function list(...items) {
  const languages = ['bg', 'en', 'fr', 'it', 'es', 'el'];
  return Object.fromEntries(languages.map((lang) => [lang, items.map((item) => item[lang] || item.bg)]));
}

const burgerPremium = { burgerEUR: 9, menuEUR: 11 };
const burgerClassic = { burgerEUR: 7, menuEUR: 9 };

const menuProducts = [
  {
    id: 'og-cheese',
    category: 'smash',
    image: './assets/images/menu/og-cheese.webp',
    badge: 'bestSeller',
    spicy: false,
    available: true,
    name: text('OG Cheese', 'OG Cheese'),
    description: text('Двоен чедър, бекон и сос 28 в класически smash профил.', 'Double cheddar, bacon and Sauce 28 in a classic smash profile.', 'Double cheddar, bacon et Sauce 28 en profil smash classique.', 'Doppio cheddar, bacon e Salsa 28 in un classico smash.', 'Doble cheddar, bacon y Salsa 28 en un smash clásico.', 'Διπλό cheddar, μπέικον και Sauce 28 σε κλασικό smash.'),
    ingredients: list(I.brioche, I.redOnion, I.sauce28, I.cheddarSlice, I.cheddarSauce, I.bacon, I.pickles, I.ketchup),
    allergens: ['gluten', 'dairy', 'egg', 'soy'],
    prices: burgerPremium,
  },
  {
    id: 'northwestern',
    category: 'smash',
    image: './assets/images/menu/northwestern.webp',
    badge: 'chefChoice',
    spicy: true,
    available: true,
    name: text('Northwestern', 'Northwestern'),
    description: text('Пикантен burger с jalapeño, бекон, Gouda и свежи зеленчуци.', 'Spicy burger with jalapeño, bacon, Gouda and fresh vegetables.', 'Burger épicé avec jalapeño, bacon, Gouda et légumes frais.', 'Burger piccante con jalapeño, bacon, Gouda e verdure fresche.', 'Burger picante con jalapeño, bacon, Gouda y verduras frescas.', 'Πικάντικο burger με jalapeño, μπέικον, Gouda και φρέσκα λαχανικά.'),
    ingredients: list(I.brioche, I.redOnion, I.hotSauce, I.cheddar, I.gouda, I.jalapeno, I.bacon, I.lettuce, I.tomato),
    allergens: ['gluten', 'dairy', 'egg', 'soy'],
    prices: burgerPremium,
  },
  {
    id: 'drill',
    category: 'smash',
    image: './assets/images/menu/drill.webp',
    spicy: false,
    available: true,
    name: text('Drill', 'Drill'),
    description: text('Опушен BBQ вкус с Gouda, пържен лук и зелена салата.', 'Smoky BBQ flavor with Gouda, fried onion and green lettuce.', 'Goût BBQ fumé avec Gouda, oignon frit et laitue verte.', 'Gusto BBQ affumicato con Gouda, cipolla fritta e lattuga verde.', 'Sabor BBQ ahumado con Gouda, cebolla frita y lechuga verde.', 'Καπνιστή BBQ γεύση με Gouda, τηγανητό κρεμμύδι και πράσινο μαρούλι.'),
    ingredients: list(I.brioche, I.friedOnion, I.greenLettuce, I.sauce28, I.bbq, I.gouda),
    allergens: ['gluten', 'dairy', 'egg', 'soy'],
    prices: burgerPremium,
  },
  {
    id: 'smacky',
    category: 'smash',
    image: './assets/images/menu/smacky.webp',
    spicy: false,
    available: true,
    name: text('Smacky', 'Smacky'),
    description: text('Печен лук, два вида сирене и специален сос.', 'Roasted onion, two cheeses and special sauce.', 'Oignon rôti, deux fromages et sauce spéciale.', 'Cipolla arrostita, due formaggi e salsa speciale.', 'Cebolla asada, dos quesos y salsa especial.', 'Ψητό κρεμμύδι, δύο τυριά και ειδική σάλτσα.'),
    ingredients: list(I.brioche, I.roastedOnion, I.cheddar, I.gouda, I.specialSauce),
    allergens: ['gluten', 'dairy', 'egg', 'mustard'],
    prices: burgerPremium,
  },
  {
    id: 'el-gringo',
    category: 'smash',
    image: './assets/images/menu/el-gringo.webp',
    spicy: true,
    available: true,
    name: text('El Gringo', 'El Gringo'),
    description: text('Лют характер с печен лук и фъстъчен killer сос.', 'Bold heat with roasted onion and killer peanut butter sauce.', 'Piquant assumé avec oignon rôti et sauce killer cacahuète.', 'Piccante deciso con cipolla arrostita e salsa killer arachidi.', 'Picante con cebolla asada y salsa killer de cacahuete.', 'Πικάντικος χαρακτήρας με ψητό κρεμμύδι και killer σάλτσα φυστικιού.'),
    ingredients: {
      bg: ['Бриош', 'Печен лук', 'Кисели краставички или Jalapeño', 'Убийствен сос с фъстъчено масло'],
      en: ['Brioche', 'Roasted onion', 'Pickles or Jalapeño', 'Killer peanut butter sauce'],
      fr: ['Brioche', 'Oignon rôti', 'Cornichons ou Jalapeño', 'Sauce killer au beurre de cacahuète'],
      it: ['Brioche', 'Cipolla arrostita', 'Cetriolini o Jalapeño', 'Salsa killer al burro di arachidi'],
      es: ['Brioche', 'Cebolla asada', 'Pepinillos o Jalapeño', 'Salsa killer de mantequilla de cacahuete'],
      el: ['Brioche', 'Ψητό κρεμμύδι', 'Πίκλες ή Jalapeño', 'Killer σάλτσα με φυστικοβούτυρο'],
    },
    allergens: ['gluten', 'dairy', 'egg', 'mustard', 'nuts', 'peanuts'],
    prices: burgerPremium,
  },
  {
    id: 'the-mayor',
    category: 'smash',
    image: './assets/images/menu/the-mayor.webp',
    spicy: false,
    available: true,
    name: text('The Mayor', 'The Mayor'),
    description: text('Богат burger с яйце, чедър, свежа салата и специален сос.', 'A rich burger with egg, cheddar, fresh lettuce and special sauce.', 'Burger généreux avec œuf, cheddar, salade fraîche et sauce spéciale.', 'Burger ricco con uovo, cheddar, insalata fresca e salsa speciale.', 'Burger completo con huevo, cheddar, lechuga fresca y salsa especial.', 'Πλούσιο burger με αυγό, cheddar, φρέσκο μαρούλι και ειδική σάλτσα.'),
    ingredients: list(I.brioche, I.redOnion, I.lettuce, I.egg, I.specialSauce, I.ketchup, I.cheddar),
    allergens: ['gluten', 'dairy', 'egg', 'mustard'],
    prices: burgerPremium,
  },
  {
    id: 'big-d',
    category: 'smash',
    image: './assets/images/menu/big-d.webp',
    spicy: false,
    available: true,
    name: text('Big D', 'Big D'),
    description: text('Свеж smash с чедър, маруля, домати и сос 28.', 'Fresh smash with cheddar, lettuce, tomato and Sauce 28.', 'Smash frais avec cheddar, salade, tomate et Sauce 28.', 'Smash fresco con cheddar, lattuga, pomodoro e Salsa 28.', 'Smash fresco con cheddar, lechuga, tomate y Salsa 28.', 'Φρέσκο smash με cheddar, μαρούλι, ντομάτα και Sauce 28.'),
    ingredients: list(I.brioche, I.cheddar, I.lettuce, I.tomato, I.redOnion, I.ketchup, I.sauce28),
    allergens: ['gluten', 'dairy', 'egg', 'soy'],
    prices: burgerPremium,
  },
  {
    id: 'maynyak',
    category: 'smash',
    image: './assets/images/menu/maynyak.webp',
    badge: 'chefChoice',
    spicy: false,
    available: true,
    name: text('Maynyak', 'Maynyak'),
    description: text('Силен signature burger с бекон, яйце, ranch, BBQ и фъстъчен сос.', 'A bold signature burger with bacon, egg, ranch, BBQ and peanut sauce.', 'Signature intense avec bacon, œuf, ranch, BBQ et sauce cacahuète.', 'Signature deciso con bacon, uovo, ranch, BBQ e salsa arachidi.', 'Signature intenso con bacon, huevo, ranch, BBQ y salsa de cacahuete.', 'Δυνατό signature burger με μπέικον, αυγό, ranch, BBQ και σάλτσα φυστικιού.'),
    ingredients: list(I.brioche, I.redOnion, I.lettuce, I.bacon, I.ranch, I.bbq, I.egg, I.peanutSauce),
    allergens: ['gluten', 'dairy', 'egg', 'mustard', 'soy', 'nuts', 'peanuts'],
    prices: burgerPremium,
  },
  {
    id: 'crunch',
    category: 'smash',
    image: './assets/images/menu/crunch.webp',
    spicy: false,
    available: true,
    name: text('Crunch', 'Crunch'),
    description: text('Минимален и плътен burger с Gouda, лук и бекон майонеза.', 'Minimal and rich with Gouda, onion and bacon mayo.', 'Minimal et riche avec Gouda, oignon et mayo bacon.', 'Minimale e intenso con Gouda, cipolla e mayo bacon.', 'Minimalista e intenso con Gouda, cebolla y mayo bacon.', 'Απλό και πλούσιο με Gouda, κρεμμύδι και μαγιονέζα μπέικον.'),
    ingredients: list(I.brioche, I.gouda, I.onion, I.mayoBacon),
    allergens: ['gluten', 'dairy', 'egg', 'mustard', 'honey'],
    prices: burgerPremium,
  },
  {
    id: 'killer',
    category: 'smash',
    image: './assets/images/menu/killer.webp',
    badge: 'bestSeller',
    spicy: false,
    available: true,
    name: text('Killer', 'Killer'),
    description: text('Легендарен burger с двоен лук, сирена и killer peanut butter sauce.', 'Legendary burger with double onion, cheeses and killer peanut butter sauce.', 'Burger légendaire avec double oignon, fromages et sauce killer cacahuète.', 'Burger leggendario con doppia cipolla, formaggi e salsa killer arachidi.', 'Burger legendario con doble cebolla, quesos y salsa killer de cacahuete.', 'Θρυλικό burger με διπλό κρεμμύδι, τυριά και killer σάλτσα φυστικιού.'),
    ingredients: list(I.brioche, I.stewedFriedOnion, I.cheddar, I.gouda, I.pickles, I.peanutSauce),
    allergens: ['gluten', 'dairy', 'egg', 'nuts', 'peanuts'],
    prices: burgerPremium,
  },
  {
    id: 'simple',
    category: 'simple',
    image: './assets/images/menu/simple.webp',
    spicy: false,
    available: true,
    name: text('Simple', 'Simple'),
    description: text('Чистият 28 вкус: бриош, чедър и сос 28.', 'The clean 28 taste: brioche, cheddar and Sauce 28.', 'Le goût 28 pur : brioche, cheddar et Sauce 28.', 'Il gusto 28 essenziale: brioche, cheddar e Salsa 28.', 'El sabor 28 directo: brioche, cheddar y Salsa 28.', 'Η καθαρή γεύση 28: brioche, cheddar και Sauce 28.'),
    ingredients: list(I.brioche, I.cheddar, I.sauce28),
    allergens: ['gluten', 'dairy', 'egg', 'soy'],
    prices: burgerClassic,
  },
  {
    id: 'ko-ko',
    category: 'chicken',
    image: './assets/images/menu/ko-ko.webp',
    spicy: false,
    available: true,
    name: text('Ko-Ko', 'Ko-Ko'),
    description: text('Пилешки burger с две филенца, сос 28 и течен чедър.', 'Chicken burger with two fillets, Sauce 28 and liquid cheddar.', 'Burger poulet avec deux filets, Sauce 28 et cheddar fondu.', 'Burger di pollo con due filetti, Salsa 28 e cheddar fuso.', 'Burger de pollo con dos filetes, Salsa 28 y cheddar líquido.', 'Burger κοτόπουλο με δύο φιλέτα, Sauce 28 και υγρό cheddar.'),
    ingredients: list(I.chicken, I.brioche, I.sauce28, I.lettuce, I.liquidCheddar, I.pickles),
    allergens: ['gluten', 'dairy', 'egg', 'nuts', 'soy'],
    prices: burgerClassic,
  },
  {
    id: 'c-chick',
    category: 'chicken',
    image: './assets/images/menu/c-chick.webp',
    spicy: false,
    available: true,
    name: text('C-Chick', 'C-Chick'),
    description: text('Пилешки burger с колслоу, бриош и сос 28.', 'Chicken burger with coleslaw, brioche and Sauce 28.', 'Burger poulet avec coleslaw, brioche et Sauce 28.', 'Burger di pollo con coleslaw, brioche e Salsa 28.', 'Burger de pollo con coleslaw, brioche y Salsa 28.', 'Burger κοτόπουλο με coleslaw, brioche και Sauce 28.'),
    ingredients: list(I.chicken, I.brioche, I.sauce28, I.coleslaw),
    allergens: ['gluten', 'dairy', 'egg', 'honey', 'mustard', 'soy', 'nuts'],
    prices: burgerClassic,
  },
  {
    id: 'veggie',
    category: 'veggie',
    image: './assets/images/menu/veggie.webp',
    spicy: false,
    available: true,
    name: text('Veggie', 'Veggie'),
    description: text('Растителен burger със соев бургер, гуакамоле и свежи зеленчуци.', 'Plant-based burger with soy patty, guacamole and fresh vegetables.', 'Burger végétal avec steak soja, guacamole et légumes frais.', 'Burger vegetale con patty di soia, guacamole e verdure fresche.', 'Burger vegetal con soja, guacamole y verduras frescas.', 'Φυτικό burger με σόγια, guacamole και φρέσκα λαχανικά.'),
    ingredients: list(I.soyBurger, I.brioche, I.mayo, I.lettuce, I.tomato, I.guacamole),
    allergens: ['gluten', 'dairy', 'egg', 'soy', 'nuts'],
    prices: burgerClassic,
  },
  {
    id: 'loaded-fries',
    category: 'fries',
    available: true,
    name: text('Loaded Fries', 'Loaded Fries', 'Loaded Fries', 'Loaded Fries', 'Loaded Fries', 'Loaded Fries'),
    description: text('Хрупкави картофи с избрана добавка и топъл чедър сос.', 'Crispy fries with your selected add-on and warm cheddar sauce.', 'Frites croustillantes avec votre supplément et sauce cheddar chaude.', 'Patatine croccanti con topping scelto e salsa cheddar calda.', 'Patatas crujientes con tu extra y salsa cheddar caliente.', 'Τραγανές πατάτες με την επιλογή σου και ζεστή σάλτσα cheddar.'),
    ingredients: text(['Картофи', 'Чедър сос'], ['Fries', 'Cheddar sauce'], ['Frites', 'Sauce cheddar'], ['Patatine', 'Salsa cheddar'], ['Patatas', 'Salsa cheddar'], ['Πατάτες', 'Σάλτσα cheddar']),
    allergens: ['dairy'],
    prices: { itemEUR: 5 },
    variants: [
      {
        id: 'cheddar',
        name: text('Cheddar', 'Cheddar', 'Cheddar', 'Cheddar', 'Cheddar', 'Cheddar'),
        image: './assets/images/menu/fries/cheddar-fries.webp',
        spicy: false,
        description: text('Класика с топъл чедър сос.', 'The classic one with warm cheddar sauce.', 'La version classique avec sauce cheddar chaude.', 'La classica con salsa cheddar calda.', 'La clásica con salsa cheddar caliente.', 'Η κλασική επιλογή με ζεστή σάλτσα cheddar.'),
        ingredients: text(['Картофи', 'Чедър сос'], ['Fries', 'Cheddar sauce'], ['Frites', 'Sauce cheddar'], ['Patatine', 'Salsa cheddar'], ['Patatas', 'Salsa cheddar'], ['Πατάτες', 'Σάλτσα cheddar']),
      },
      {
        id: 'bacon',
        name: text('Bacon', 'Bacon', 'Bacon', 'Bacon', 'Bacon', 'Bacon'),
        image: './assets/images/menu/fries/add-bacon-fries.webp',
        spicy: false,
        description: text('Чедър картофи с хрупкав бекон.', 'Cheddar fries with crispy bacon.', 'Frites cheddar avec bacon croustillant.', 'Patatine cheddar con bacon croccante.', 'Patatas cheddar con bacon crujiente.', 'Πατάτες cheddar με τραγανό μπέικον.'),
        ingredients: text(['Картофи', 'Чедър сос', 'Бекон'], ['Fries', 'Cheddar sauce', 'Bacon'], ['Frites', 'Sauce cheddar', 'Bacon'], ['Patatine', 'Salsa cheddar', 'Bacon'], ['Patatas', 'Salsa cheddar', 'Bacon'], ['Πατάτες', 'Σάλτσα cheddar', 'Μπέικον']),
      },
      {
        id: 'jalapeno',
        name: text('Jalapeño', 'Jalapeño', 'Jalapeño', 'Jalapeño', 'Jalapeño', 'Jalapeño'),
        image: './assets/images/menu/fries/add-jalapeno-fries.webp',
        spicy: true,
        description: text('Чедър картофи с пикантно Jalapeño.', 'Cheddar fries with spicy Jalapeño.', 'Frites cheddar avec Jalapeño épicé.', 'Patatine cheddar con Jalapeño piccante.', 'Patatas cheddar con Jalapeño picante.', 'Πατάτες cheddar με πικάντικο Jalapeño.'),
        ingredients: text(['Картофи', 'Чедър сос', 'Jalapeño'], ['Fries', 'Cheddar sauce', 'Jalapeño'], ['Frites', 'Sauce cheddar', 'Jalapeño'], ['Patatine', 'Salsa cheddar', 'Jalapeño'], ['Patatas', 'Salsa cheddar', 'Jalapeño'], ['Πατάτες', 'Σάλτσα cheddar', 'Jalapeño']),
      },
      {
        id: 'mix',
        name: text('Mix It', 'Mix It', 'Mix It', 'Mix It', 'Mix It', 'Mix It'),
        image: './assets/images/menu/fries/mix-it-fries.webp',
        spicy: true,
        description: text('Пълният вариант: чедър, бекон и Jalapeño.', 'The full version: cheddar, bacon and Jalapeño.', 'La totale : cheddar, bacon et Jalapeño.', 'La versione completa: cheddar, bacon e Jalapeño.', 'La versión completa: cheddar, bacon y Jalapeño.', 'Η πλήρης επιλογή: cheddar, μπέικον και Jalapeño.'),
        ingredients: text(['Картофи', 'Чедър сос', 'Бекон', 'Jalapeño'], ['Fries', 'Cheddar sauce', 'Bacon', 'Jalapeño'], ['Frites', 'Sauce cheddar', 'Bacon', 'Jalapeño'], ['Patatine', 'Salsa cheddar', 'Bacon', 'Jalapeño'], ['Patatas', 'Salsa cheddar', 'Bacon', 'Jalapeño'], ['Πατάτες', 'Σάλτσα cheddar', 'Μπέικον', 'Jalapeño']),
      },
    ],
  },
  {
    id: 'fuzetea-forest-fruit',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/forest.png',
    name: text('Fuzetea Iced Tea Forest Fruit 500мл', 'Fuzetea Iced Tea Forest Fruit 500ml'),
    description: text(
      'FUZETEA черен чай горски плодове е освежаваща напитка чай с малко калории, фюжън от черен чай и горски плодове.',
      'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'fuzetea-peach-hibiscus',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/peach.png',
    name: text('Студен Чай Fuzetea Праскова И Хибискус 500мл', 'Fuzetea Peach & Hibiscus Iced Tea 500ml'),
    description: text(
      'FUZETEA черен чай праскова и хибискус е освежаваща напитка чай с малко калории, фюжън от черен чай, праскова и хибискус.',
      'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'coca-cola-original',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/cola1.png',
    name: text('Coca-Cola Original Taste 500мл', 'Coca-Cola Original Taste 500ml'),
    description: text(
      'Coca-Cola Original Taste е вкусна и освежаваща газирана напитка с отличен вкус.',
      'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'fuzetea-lemon-lemongrass',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/lemon.png',
    name: text('Студен Чай Fuzetea Лимон И Лимонена Трева 500мл', 'Fuzetea Lemon & Lemongrass Iced Tea 500ml'),
    description: text(
      'FUZETEA черен чай лимон и лимонова трева е освежаваща напитка чай с малко калории, фюжън от черен чай, лимон и лимонова трева.',
      'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'fanta-orange',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/fanta1.png',
    name: text('Fanta Портокал 500мл', 'Fanta Orange 500ml'),
    description: text(
      'Fanta утолява жаждата и освежава – винаги до теб, когато искаш да си подариш награда.',
      'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'fanta-grape',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/fantagrape.png',
    name: text('Fanta Грозде 500мл', 'Fanta Grape 500ml'),
    description: text(
      'Освежаваща газирана напитка с вкус на грозде.',
      'Refreshing sparkling drink with grape flavor.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'fanta-lemon',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/fantalemon.png',
    name: text('Fanta Лимон 500мл', 'Fanta Lemon 500ml'),
    description: text(
      'Освежаваща газирана напитка с вкус на лимон.',
      'Refreshing sparkling drink with lemon flavor.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'coca-cola-zero',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/cocacolazero.png',
    name: text('Coca-Cola Zero 500мл', 'Coca-Cola Zero 500ml'),
    description: text(
      'Coca-Cola без захар – класически вкус, нула захар.',
      'Coca-Cola without sugar - classic taste, zero sugar.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'bankya-water',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/water1.png',
    name: text('Минерална Вода Банкя 500мл', 'Bankya Mineral Water 500ml'),
    description: text(
      'Банкя е натурална минерална вода с ниска минерализация, подходяща за ежедневна консумация.',
      'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 1 },
  },
  {
    id: 'fuzetea-mango-pineapple',
    category: 'drinks',
    subcategory: 'soft',
    available: true,
    image: './assets/images/pineapple.png',
    name: text('Студен Чай Fuzetea Манго И Ананас 500мл', 'Fuzetea Mango & Pineapple Iced Tea 500ml'),
    description: text(
      'FUZETEA черен чай манго и ананас е освежаваща напитка чай с малко калории, фюжън от черен чай, манго и ананас.',
      'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'stella-artois-can',
    category: 'drinks',
    subcategory: 'beer',
    available: true,
    image: './assets/images/stela1.png',
    name: text('Стела Артоа Кен 500мл', 'Stella Artois Can 500ml'),
    description: text(
      'Бира Stella Artois кен 500мл.',
      'Stella Artois beer can 500ml.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 3 },
  },
  {
    id: 'kamenitza-can',
    category: 'drinks',
    subcategory: 'beer',
    available: true,
    image: './assets/images/kame1.png',
    name: text('Каменица Кен 500мл', 'Kamenitza Can 500ml'),
    description: text(
      'Бира Каменица кен 500мл.',
      'Kamenitza beer can 500ml.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2 },
  },
  {
    id: 'corona-330',
    category: 'drinks',
    subcategory: 'beer',
    available: true,
    image: './assets/images/corona1.png',
    name: text('Corona 330мл', 'Corona 330ml'),
    description: text(
      'Бира Corona 330мл.',
      'Corona beer 330ml.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 4.5 },
  },
  {
    id: 'madri-500',
    category: 'drinks',
    subcategory: 'beer',
    available: true,
    image: './assets/images/madri.png',
    name: text('Мадри 500мл', 'Madri 500ml'),
    description: text(
      'Бира Мадри 500мл.',
      'Madri beer 500ml.'
    ),
    ingredients: text([], []),
    allergens: [],
    prices: { itemEUR: 2.5 },
  },
];
