INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Smash', 'smash', 'Smash', 'Smash', 'Smash', 'Smash', 'Smash', 'Smash', 1, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Simple', 'simple', 'Simple', 'Simple', 'Simple', 'Simple', 'Simple', 'Simple', 2, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Пилешко', 'chicken', 'Пилешко', 'Chicken', 'Poulet', 'Pollo', 'Pollo', 'Κοτόπουλο', 3, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Veggie', 'veggie', 'Veggie', 'Veggie', 'Veggie', 'Veggie', 'Veggie', 'Veggie', 4, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Fries', 'fries', 'Fries', 'Fries', 'Frites', 'Patatine', 'Patatas', 'Πατάτες', 5, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Безалкохолни', 'drinks', 'Безалкохолни', 'Soft Drinks', 'Boissons Sans Alcool', 'Bevande Analcoliche', 'Bebidas Sin Alcohol', 'Αναψυκτικά', 6, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO categories (name, slug, title_bg, title_en, title_fr, title_it, title_es, title_el, sort_order, is_active)
VALUES ('Бира', 'beer', 'Бира', 'Beer', 'Bière', 'Birra', 'Cerveza', 'Μπίρα', 7, 1)
ON CONFLICT(slug) DO UPDATE SET
  name = excluded.name,
  title_bg = excluded.title_bg,
  title_en = excluded.title_en,
  title_fr = excluded.title_fr,
  title_it = excluded.title_it,
  title_es = excluded.title_es,
  title_el = excluded.title_el,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'og-cheese',
  'OG Cheese',
  'Двоен чедър, бекон и сос 28 в класически smash профил.',
  'OG Cheese',
  'OG Cheese',
  'OG Cheese',
  'OG Cheese',
  'OG Cheese',
  'OG Cheese',
  'Двоен чедър, бекон и сос 28 в класически smash профил.',
  'Double cheddar, bacon and Sauce 28 in a classic smash profile.',
  'Double cheddar, bacon et Sauce 28 en profil smash classique.',
  'Doppio cheddar, bacon e Salsa 28 in un classico smash.',
  'Doble cheddar, bacon y Salsa 28 en un smash clásico.',
  'Διπλό cheddar, μπέικον και Sauce 28 σε κλασικό smash.',
  9,
  './assets/images/menu/og-cheese.webp',
  './assets/images/menu/og-cheese.webp',
  'OG Cheese',
  1,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'northwestern',
  'Northwestern',
  'Пикантен burger с jalapeño, бекон, Gouda и свежи зеленчуци.',
  'Northwestern',
  'Northwestern',
  'Northwestern',
  'Northwestern',
  'Northwestern',
  'Northwestern',
  'Пикантен burger с jalapeño, бекон, Gouda и свежи зеленчуци.',
  'Spicy burger with jalapeño, bacon, Gouda and fresh vegetables.',
  'Burger épicé avec jalapeño, bacon, Gouda et légumes frais.',
  'Burger piccante con jalapeño, bacon, Gouda e verdure fresche.',
  'Burger picante con jalapeño, bacon, Gouda y verduras frescas.',
  'Πικάντικο burger με jalapeño, μπέικον, Gouda και φρέσκα λαχανικά.',
  9,
  './assets/images/menu/northwestern.webp',
  './assets/images/menu/northwestern.webp',
  'Northwestern',
  2,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'drill',
  'Drill',
  'Опушен BBQ вкус с Gouda, пържен лук и зелена салата.',
  'Drill',
  'Drill',
  'Drill',
  'Drill',
  'Drill',
  'Drill',
  'Опушен BBQ вкус с Gouda, пържен лук и зелена салата.',
  'Smoky BBQ flavor with Gouda, fried onion and green lettuce.',
  'Goût BBQ fumé avec Gouda, oignon frit et laitue verte.',
  'Gusto BBQ affumicato con Gouda, cipolla fritta e lattuga verde.',
  'Sabor BBQ ahumado con Gouda, cebolla frita y lechuga verde.',
  'Καπνιστή BBQ γεύση με Gouda, τηγανητό κρεμμύδι και πράσινο μαρούλι.',
  9,
  './assets/images/menu/drill.webp',
  './assets/images/menu/drill.webp',
  'Drill',
  3,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'smacky',
  'Smacky',
  'Печен лук, два вида сирене и специален сос.',
  'Smacky',
  'Smacky',
  'Smacky',
  'Smacky',
  'Smacky',
  'Smacky',
  'Печен лук, два вида сирене и специален сос.',
  'Roasted onion, two cheeses and special sauce.',
  'Oignon rôti, deux fromages et sauce spéciale.',
  'Cipolla arrostita, due formaggi e salsa speciale.',
  'Cebolla asada, dos quesos y salsa especial.',
  'Ψητό κρεμμύδι, δύο τυριά και ειδική σάλτσα.',
  9,
  './assets/images/menu/smacky.webp',
  './assets/images/menu/smacky.webp',
  'Smacky',
  4,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'el-gringo',
  'El Gringo',
  'Лют характер с печен лук и фъстъчен killer сос.',
  'El Gringo',
  'El Gringo',
  'El Gringo',
  'El Gringo',
  'El Gringo',
  'El Gringo',
  'Лют характер с печен лук и фъстъчен killer сос.',
  'Bold heat with roasted onion and killer peanut butter sauce.',
  'Piquant assumé avec oignon rôti et sauce killer cacahuète.',
  'Piccante deciso con cipolla arrostita e salsa killer arachidi.',
  'Picante con cebolla asada y salsa killer de cacahuete.',
  'Πικάντικος χαρακτήρας με ψητό κρεμμύδι και killer σάλτσα φυστικιού.',
  9,
  './assets/images/menu/el-gringo.webp',
  './assets/images/menu/el-gringo.webp',
  'El Gringo',
  5,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'the-mayor',
  'The Mayor',
  'Богат burger с яйце, чедър, свежа салата и специален сос.',
  'The Mayor',
  'The Mayor',
  'The Mayor',
  'The Mayor',
  'The Mayor',
  'The Mayor',
  'Богат burger с яйце, чедър, свежа салата и специален сос.',
  'A rich burger with egg, cheddar, fresh lettuce and special sauce.',
  'Burger généreux avec œuf, cheddar, salade fraîche et sauce spéciale.',
  'Burger ricco con uovo, cheddar, insalata fresca e salsa speciale.',
  'Burger completo con huevo, cheddar, lechuga fresca y salsa especial.',
  'Πλούσιο burger με αυγό, cheddar, φρέσκο μαρούλι και ειδική σάλτσα.',
  9,
  './assets/images/menu/the-mayor.webp',
  './assets/images/menu/the-mayor.webp',
  'The Mayor',
  6,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'big-d',
  'Big D',
  'Свеж smash с чедър, маруля, домати и сос 28.',
  'Big D',
  'Big D',
  'Big D',
  'Big D',
  'Big D',
  'Big D',
  'Свеж smash с чедър, маруля, домати и сос 28.',
  'Fresh smash with cheddar, lettuce, tomato and Sauce 28.',
  'Smash frais avec cheddar, salade, tomate et Sauce 28.',
  'Smash fresco con cheddar, lattuga, pomodoro e Salsa 28.',
  'Smash fresco con cheddar, lechuga, tomate y Salsa 28.',
  'Φρέσκο smash με cheddar, μαρούλι, ντομάτα και Sauce 28.',
  9,
  './assets/images/menu/big-d.webp',
  './assets/images/menu/big-d.webp',
  'Big D',
  7,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'maynyak',
  'Maynyak',
  'Силен signature burger с бекон, яйце, ranch, BBQ и фъстъчен сос.',
  'Maynyak',
  'Maynyak',
  'Maynyak',
  'Maynyak',
  'Maynyak',
  'Maynyak',
  'Силен signature burger с бекон, яйце, ranch, BBQ и фъстъчен сос.',
  'A bold signature burger with bacon, egg, ranch, BBQ and peanut sauce.',
  'Signature intense avec bacon, œuf, ranch, BBQ et sauce cacahuète.',
  'Signature deciso con bacon, uovo, ranch, BBQ e salsa arachidi.',
  'Signature intenso con bacon, huevo, ranch, BBQ y salsa de cacahuete.',
  'Δυνατό signature burger με μπέικον, αυγό, ranch, BBQ και σάλτσα φυστικιού.',
  9,
  './assets/images/menu/maynyak.webp',
  './assets/images/menu/maynyak.webp',
  'Maynyak',
  8,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'crunch',
  'Crunch',
  'Минимален и плътен burger с Gouda, лук и бекон майонеза.',
  'Crunch',
  'Crunch',
  'Crunch',
  'Crunch',
  'Crunch',
  'Crunch',
  'Минимален и плътен burger с Gouda, лук и бекон майонеза.',
  'Minimal and rich with Gouda, onion and bacon mayo.',
  'Minimal et riche avec Gouda, oignon et mayo bacon.',
  'Minimale e intenso con Gouda, cipolla e mayo bacon.',
  'Minimalista e intenso con Gouda, cebolla y mayo bacon.',
  'Απλό και πλούσιο με Gouda, κρεμμύδι και μαγιονέζα μπέικον.',
  9,
  './assets/images/menu/crunch.webp',
  './assets/images/menu/crunch.webp',
  'Crunch',
  9,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'smash'),
  'killer',
  'Killer',
  'Легендарен burger с двоен лук, сирена и killer peanut butter sauce.',
  'Killer',
  'Killer',
  'Killer',
  'Killer',
  'Killer',
  'Killer',
  'Легендарен burger с двоен лук, сирена и killer peanut butter sauce.',
  'Legendary burger with double onion, cheeses and killer peanut butter sauce.',
  'Burger légendaire avec double oignon, fromages et sauce killer cacahuète.',
  'Burger leggendario con doppia cipolla, formaggi e salsa killer arachidi.',
  'Burger legendario con doble cebolla, quesos y salsa killer de cacahuete.',
  'Θρυλικό burger με διπλό κρεμμύδι, τυριά και killer σάλτσα φυστικιού.',
  9,
  './assets/images/menu/killer.webp',
  './assets/images/menu/killer.webp',
  'Killer',
  10,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'simple'),
  'simple',
  'Simple',
  'Чистият 28 вкус: бриош, чедър и сос 28.',
  'Simple',
  'Simple',
  'Simple',
  'Simple',
  'Simple',
  'Simple',
  'Чистият 28 вкус: бриош, чедър и сос 28.',
  'The clean 28 taste: brioche, cheddar and Sauce 28.',
  'Le goût 28 pur : brioche, cheddar et Sauce 28.',
  'Il gusto 28 essenziale: brioche, cheddar e Salsa 28.',
  'El sabor 28 directo: brioche, cheddar y Salsa 28.',
  'Η καθαρή γεύση 28: brioche, cheddar και Sauce 28.',
  7,
  './assets/images/menu/simple.webp',
  './assets/images/menu/simple.webp',
  'Simple',
  11,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'chicken'),
  'ko-ko',
  'Ko-Ko',
  'Пилешки burger с две филенца, сос 28 и течен чедър.',
  'Ko-Ko',
  'Ko-Ko',
  'Ko-Ko',
  'Ko-Ko',
  'Ko-Ko',
  'Ko-Ko',
  'Пилешки burger с две филенца, сос 28 и течен чедър.',
  'Chicken burger with two fillets, Sauce 28 and liquid cheddar.',
  'Burger poulet avec deux filets, Sauce 28 et cheddar fondu.',
  'Burger di pollo con due filetti, Salsa 28 e cheddar fuso.',
  'Burger de pollo con dos filetes, Salsa 28 y cheddar líquido.',
  'Burger κοτόπουλο με δύο φιλέτα, Sauce 28 και υγρό cheddar.',
  7,
  './assets/images/menu/ko-ko.webp',
  './assets/images/menu/ko-ko.webp',
  'Ko-Ko',
  12,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'chicken'),
  'c-chick',
  'C-Chick',
  'Пилешки burger с колслоу, бриош и сос 28.',
  'C-Chick',
  'C-Chick',
  'C-Chick',
  'C-Chick',
  'C-Chick',
  'C-Chick',
  'Пилешки burger с колслоу, бриош и сос 28.',
  'Chicken burger with coleslaw, brioche and Sauce 28.',
  'Burger poulet avec coleslaw, brioche et Sauce 28.',
  'Burger di pollo con coleslaw, brioche e Salsa 28.',
  'Burger de pollo con coleslaw, brioche y Salsa 28.',
  'Burger κοτόπουλο με coleslaw, brioche και Sauce 28.',
  7,
  './assets/images/menu/c-chick.webp',
  './assets/images/menu/c-chick.webp',
  'C-Chick',
  13,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'veggie'),
  'veggie',
  'Veggie',
  'Растителен burger със соев бургер, гуакамоле и свежи зеленчуци.',
  'Veggie',
  'Veggie',
  'Veggie',
  'Veggie',
  'Veggie',
  'Veggie',
  'Растителен burger със соев бургер, гуакамоле и свежи зеленчуци.',
  'Plant-based burger with soy patty, guacamole and fresh vegetables.',
  'Burger végétal avec steak soja, guacamole et légumes frais.',
  'Burger vegetale con patty di soia, guacamole e verdure fresche.',
  'Burger vegetal con soja, guacamole y verduras frescas.',
  'Φυτικό burger με σόγια, guacamole και φρέσκα λαχανικά.',
  7,
  './assets/images/menu/veggie.webp',
  './assets/images/menu/veggie.webp',
  'Veggie',
  14,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'fries'),
  'loaded-fries',
  'Loaded Fries',
  'Хрупкави картофи с избрана добавка и топъл чедър сос.',
  'Loaded Fries',
  'Loaded Fries',
  'Loaded Fries',
  'Loaded Fries',
  'Loaded Fries',
  'Loaded Fries',
  'Хрупкави картофи с избрана добавка и топъл чедър сос.',
  'Crispy fries with your selected add-on and warm cheddar sauce.',
  'Frites croustillantes avec votre supplément et sauce cheddar chaude.',
  'Patatine croccanti con topping scelto e salsa cheddar calda.',
  'Patatas crujientes con tu extra y salsa cheddar caliente.',
  'Τραγανές πατάτες με την επιλογή σου και ζεστή σάλτσα cheddar.',
  5,
  '',
  '',
  'Loaded Fries',
  15,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fuzetea-forest-fruit',
  'Fuzetea Iced Tea Forest Fruit 500мл',
  'FUZETEA черен чай горски плодове е освежаваща напитка чай с малко калории, фюжън от черен чай и горски плодове.',
  'Fuzetea Iced Tea Forest Fruit 500мл',
  'Fuzetea Iced Tea Forest Fruit 500ml',
  'Fuzetea Iced Tea Forest Fruit 500ml',
  'Fuzetea Iced Tea Forest Fruit 500ml',
  'Fuzetea Iced Tea Forest Fruit 500ml',
  'Fuzetea Iced Tea Forest Fruit 500ml',
  'FUZETEA черен чай горски плодове е освежаваща напитка чай с малко калории, фюжън от черен чай и горски плодове.',
  'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.',
  'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.',
  'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.',
  'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.',
  'FUZETEA black tea forest fruit is a refreshing low-calorie tea drink, a fusion of black tea and forest fruits.',
  2,
  './assets/images/forest.png',
  './assets/images/forest.png',
  'Fuzetea Iced Tea Forest Fruit 500мл',
  16,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fuzetea-peach-hibiscus',
  'Студен Чай Fuzetea Праскова И Хибискус 500мл',
  'FUZETEA черен чай праскова и хибискус е освежаваща напитка чай с малко калории, фюжън от черен чай, праскова и хибискус.',
  'Студен Чай Fuzetea Праскова И Хибискус 500мл',
  'Fuzetea Peach & Hibiscus Iced Tea 500ml',
  'Fuzetea Peach & Hibiscus Iced Tea 500ml',
  'Fuzetea Peach & Hibiscus Iced Tea 500ml',
  'Fuzetea Peach & Hibiscus Iced Tea 500ml',
  'Fuzetea Peach & Hibiscus Iced Tea 500ml',
  'FUZETEA черен чай праскова и хибискус е освежаваща напитка чай с малко калории, фюжън от черен чай, праскова и хибискус.',
  'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.',
  'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.',
  'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.',
  'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.',
  'FUZETEA black tea peach and hibiscus is a refreshing low-calorie tea drink, a fusion of black tea, peach and hibiscus.',
  2,
  './assets/images/peach.png',
  './assets/images/peach.png',
  'Студен Чай Fuzetea Праскова И Хибискус 500мл',
  17,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'coca-cola-original',
  'Coca-Cola Original Taste 500мл',
  'Coca-Cola Original Taste е вкусна и освежаваща газирана напитка с отличен вкус.',
  'Coca-Cola Original Taste 500мл',
  'Coca-Cola Original Taste 500ml',
  'Coca-Cola Original Taste 500ml',
  'Coca-Cola Original Taste 500ml',
  'Coca-Cola Original Taste 500ml',
  'Coca-Cola Original Taste 500ml',
  'Coca-Cola Original Taste е вкусна и освежаваща газирана напитка с отличен вкус.',
  'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.',
  'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.',
  'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.',
  'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.',
  'Coca-Cola Original Taste is a delicious and refreshing sparkling drink with a classic taste.',
  2,
  './assets/images/cola1.png',
  './assets/images/cola1.png',
  'Coca-Cola Original Taste 500мл',
  18,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fuzetea-lemon-lemongrass',
  'Студен Чай Fuzetea Лимон И Лимонена Трева 500мл',
  'FUZETEA черен чай лимон и лимонова трева е освежаваща напитка чай с малко калории, фюжън от черен чай, лимон и лимонова трева.',
  'Студен Чай Fuzetea Лимон И Лимонена Трева 500мл',
  'Fuzetea Lemon & Lemongrass Iced Tea 500ml',
  'Fuzetea Lemon & Lemongrass Iced Tea 500ml',
  'Fuzetea Lemon & Lemongrass Iced Tea 500ml',
  'Fuzetea Lemon & Lemongrass Iced Tea 500ml',
  'Fuzetea Lemon & Lemongrass Iced Tea 500ml',
  'FUZETEA черен чай лимон и лимонова трева е освежаваща напитка чай с малко калории, фюжън от черен чай, лимон и лимонова трева.',
  'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.',
  'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.',
  'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.',
  'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.',
  'FUZETEA black tea lemon and lemongrass is a refreshing low-calorie tea drink, a fusion of black tea, lemon and lemongrass.',
  2,
  './assets/images/lemon.png',
  './assets/images/lemon.png',
  'Студен Чай Fuzetea Лимон И Лимонена Трева 500мл',
  19,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fanta-orange',
  'Fanta Портокал 500мл',
  'Fanta утолява жаждата и освежава – винаги до теб, когато искаш да си подариш награда.',
  'Fanta Портокал 500мл',
  'Fanta Orange 500ml',
  'Fanta Orange 500ml',
  'Fanta Orange 500ml',
  'Fanta Orange 500ml',
  'Fanta Orange 500ml',
  'Fanta утолява жаждата и освежава – винаги до теб, когато искаш да си подариш награда.',
  'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.',
  'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.',
  'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.',
  'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.',
  'Fanta quenches your thirst and refreshes you - always there when you want to treat yourself.',
  2,
  './assets/images/fanta1.png',
  './assets/images/fanta1.png',
  'Fanta Портокал 500мл',
  20,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fanta-grape',
  'Fanta Грозде 500мл',
  'Освежаваща газирана напитка с вкус на грозде.',
  'Fanta Грозде 500мл',
  'Fanta Grape 500ml',
  'Fanta Grape 500ml',
  'Fanta Grape 500ml',
  'Fanta Grape 500ml',
  'Fanta Grape 500ml',
  'Освежаваща газирана напитка с вкус на грозде.',
  'Refreshing sparkling drink with grape flavor.',
  'Refreshing sparkling drink with grape flavor.',
  'Refreshing sparkling drink with grape flavor.',
  'Refreshing sparkling drink with grape flavor.',
  'Refreshing sparkling drink with grape flavor.',
  2,
  './assets/images/fantagrape.png',
  './assets/images/fantagrape.png',
  'Fanta Грозде 500мл',
  21,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fanta-lemon',
  'Fanta Лимон 500мл',
  'Освежаваща газирана напитка с вкус на лимон.',
  'Fanta Лимон 500мл',
  'Fanta Lemon 500ml',
  'Fanta Lemon 500ml',
  'Fanta Lemon 500ml',
  'Fanta Lemon 500ml',
  'Fanta Lemon 500ml',
  'Освежаваща газирана напитка с вкус на лимон.',
  'Refreshing sparkling drink with lemon flavor.',
  'Refreshing sparkling drink with lemon flavor.',
  'Refreshing sparkling drink with lemon flavor.',
  'Refreshing sparkling drink with lemon flavor.',
  'Refreshing sparkling drink with lemon flavor.',
  2,
  './assets/images/fantalemon.png',
  './assets/images/fantalemon.png',
  'Fanta Лимон 500мл',
  22,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'coca-cola-zero',
  'Coca-Cola Zero 500мл',
  'Coca-Cola без захар – класически вкус, нула захар.',
  'Coca-Cola Zero 500мл',
  'Coca-Cola Zero 500ml',
  'Coca-Cola Zero 500ml',
  'Coca-Cola Zero 500ml',
  'Coca-Cola Zero 500ml',
  'Coca-Cola Zero 500ml',
  'Coca-Cola без захар – класически вкус, нула захар.',
  'Coca-Cola without sugar - classic taste, zero sugar.',
  'Coca-Cola without sugar - classic taste, zero sugar.',
  'Coca-Cola without sugar - classic taste, zero sugar.',
  'Coca-Cola without sugar - classic taste, zero sugar.',
  'Coca-Cola without sugar - classic taste, zero sugar.',
  2,
  './assets/images/cocacolazero.png',
  './assets/images/cocacolazero.png',
  'Coca-Cola Zero 500мл',
  23,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'bankya-water',
  'Минерална Вода Банкя 500мл',
  'Банкя е натурална минерална вода с ниска минерализация, подходяща за ежедневна консумация.',
  'Минерална Вода Банкя 500мл',
  'Bankya Mineral Water 500ml',
  'Bankya Mineral Water 500ml',
  'Bankya Mineral Water 500ml',
  'Bankya Mineral Water 500ml',
  'Bankya Mineral Water 500ml',
  'Банкя е натурална минерална вода с ниска минерализация, подходяща за ежедневна консумация.',
  'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.',
  'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.',
  'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.',
  'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.',
  'Bankya is natural mineral water with low mineralization, suitable for everyday consumption.',
  1,
  './assets/images/water1.png',
  './assets/images/water1.png',
  'Минерална Вода Банкя 500мл',
  24,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'drinks'),
  'fuzetea-mango-pineapple',
  'Студен Чай Fuzetea Манго И Ананас 500мл',
  'FUZETEA черен чай манго и ананас е освежаваща напитка чай с малко калории, фюжън от черен чай, манго и ананас.',
  'Студен Чай Fuzetea Манго И Ананас 500мл',
  'Fuzetea Mango & Pineapple Iced Tea 500ml',
  'Fuzetea Mango & Pineapple Iced Tea 500ml',
  'Fuzetea Mango & Pineapple Iced Tea 500ml',
  'Fuzetea Mango & Pineapple Iced Tea 500ml',
  'Fuzetea Mango & Pineapple Iced Tea 500ml',
  'FUZETEA черен чай манго и ананас е освежаваща напитка чай с малко калории, фюжън от черен чай, манго и ананас.',
  'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.',
  'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.',
  'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.',
  'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.',
  'FUZETEA black tea mango and pineapple is a refreshing low-calorie tea drink, a fusion of black tea, mango and pineapple.',
  2,
  './assets/images/pineapple.png',
  './assets/images/pineapple.png',
  'Студен Чай Fuzetea Манго И Ананас 500мл',
  25,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'beer'),
  'stella-artois-can',
  'Стела Артоа Кен 500мл',
  'Бира Stella Artois кен 500мл.',
  'Стела Артоа Кен 500мл',
  'Stella Artois Can 500ml',
  'Stella Artois Can 500ml',
  'Stella Artois Can 500ml',
  'Stella Artois Can 500ml',
  'Stella Artois Can 500ml',
  'Бира Stella Artois кен 500мл.',
  'Stella Artois beer can 500ml.',
  'Stella Artois beer can 500ml.',
  'Stella Artois beer can 500ml.',
  'Stella Artois beer can 500ml.',
  'Stella Artois beer can 500ml.',
  3,
  './assets/images/stela1.png',
  './assets/images/stela1.png',
  'Стела Артоа Кен 500мл',
  26,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'beer'),
  'kamenitza-can',
  'Каменица Кен 500мл',
  'Бира Каменица кен 500мл.',
  'Каменица Кен 500мл',
  'Kamenitza Can 500ml',
  'Kamenitza Can 500ml',
  'Kamenitza Can 500ml',
  'Kamenitza Can 500ml',
  'Kamenitza Can 500ml',
  'Бира Каменица кен 500мл.',
  'Kamenitza beer can 500ml.',
  'Kamenitza beer can 500ml.',
  'Kamenitza beer can 500ml.',
  'Kamenitza beer can 500ml.',
  'Kamenitza beer can 500ml.',
  2,
  './assets/images/kame1.png',
  './assets/images/kame1.png',
  'Каменица Кен 500мл',
  27,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'beer'),
  'corona-330',
  'Corona 330мл',
  'Бира Corona 330мл.',
  'Corona 330мл',
  'Corona 330ml',
  'Corona 330ml',
  'Corona 330ml',
  'Corona 330ml',
  'Corona 330ml',
  'Бира Corona 330мл.',
  'Corona beer 330ml.',
  'Corona beer 330ml.',
  'Corona beer 330ml.',
  'Corona beer 330ml.',
  'Corona beer 330ml.',
  4.5,
  './assets/images/corona1.png',
  './assets/images/corona1.png',
  'Corona 330мл',
  28,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO menu_items (
  category_id,
  slug,
  name,
  description,
  name_bg,
  name_en,
  name_fr,
  name_it,
  name_es,
  name_el,
  description_bg,
  description_en,
  description_fr,
  description_it,
  description_es,
  description_el,
  price,
  image_url,
  image_key,
  image_alt,
  sort_order,
  is_active,
  is_available
)
VALUES (
  (SELECT id FROM categories WHERE slug = 'beer'),
  'madri-500',
  'Мадри 500мл',
  'Бира Мадри 500мл.',
  'Мадри 500мл',
  'Madri 500ml',
  'Madri 500ml',
  'Madri 500ml',
  'Madri 500ml',
  'Madri 500ml',
  'Бира Мадри 500мл.',
  'Madri beer 500ml.',
  'Madri beer 500ml.',
  'Madri beer 500ml.',
  'Madri beer 500ml.',
  'Madri beer 500ml.',
  2.5,
  './assets/images/madri.png',
  './assets/images/madri.png',
  'Мадри 500мл',
  29,
  1,
  1
)
ON CONFLICT(slug) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  name_bg = excluded.name_bg,
  name_en = excluded.name_en,
  name_fr = excluded.name_fr,
  name_it = excluded.name_it,
  name_es = excluded.name_es,
  name_el = excluded.name_el,
  description_bg = excluded.description_bg,
  description_en = excluded.description_en,
  description_fr = excluded.description_fr,
  description_it = excluded.description_it,
  description_es = excluded.description_es,
  description_el = excluded.description_el,
  price = excluded.price,
  image_url = excluded.image_url,
  image_key = excluded.image_key,
  image_alt = excluded.image_alt,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active,
  is_available = excluded.is_available,
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO gallery_images (title, alt, image_url, image_key, sort_order, is_active)
SELECT '28 GRILL burger photo', '28 GRILL burger photo', 'assets/gallery/gallery-1.webp', 'gallery-1', 1, 1
WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE image_url = 'assets/gallery/gallery-1.webp');

UPDATE gallery_images
SET
  title = '28 GRILL burger photo',
  alt = '28 GRILL burger photo',
  image_key = 'gallery-1',
  sort_order = 1,
  is_active = 1,
  updated_at = CURRENT_TIMESTAMP
WHERE image_url = 'assets/gallery/gallery-1.webp';

INSERT INTO gallery_images (title, alt, image_url, image_key, sort_order, is_active)
SELECT '28 GRILL smash burger', '28 GRILL smash burger', 'assets/gallery/gallery-2.webp', 'gallery-2', 2, 1
WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE image_url = 'assets/gallery/gallery-2.webp');

UPDATE gallery_images
SET
  title = '28 GRILL smash burger',
  alt = '28 GRILL smash burger',
  image_key = 'gallery-2',
  sort_order = 2,
  is_active = 1,
  updated_at = CURRENT_TIMESTAMP
WHERE image_url = 'assets/gallery/gallery-2.webp';

INSERT INTO gallery_images (title, alt, image_url, image_key, sort_order, is_active)
SELECT '28 GRILL crispy burger', '28 GRILL crispy burger', 'assets/gallery/gallery-3.webp', 'gallery-3', 3, 1
WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE image_url = 'assets/gallery/gallery-3.webp');

UPDATE gallery_images
SET
  title = '28 GRILL crispy burger',
  alt = '28 GRILL crispy burger',
  image_key = 'gallery-3',
  sort_order = 3,
  is_active = 1,
  updated_at = CURRENT_TIMESTAMP
WHERE image_url = 'assets/gallery/gallery-3.webp';

INSERT INTO gallery_images (title, alt, image_url, image_key, sort_order, is_active)
SELECT '28 GRILL Kapana moment', '28 GRILL Kapana moment', 'assets/gallery/gallery-4.webp', 'gallery-4', 4, 1
WHERE NOT EXISTS (SELECT 1 FROM gallery_images WHERE image_url = 'assets/gallery/gallery-4.webp');

UPDATE gallery_images
SET
  title = '28 GRILL Kapana moment',
  alt = '28 GRILL Kapana moment',
  image_key = 'gallery-4',
  sort_order = 4,
  is_active = 1,
  updated_at = CURRENT_TIMESTAMP
WHERE image_url = 'assets/gallery/gallery-4.webp';
